# Generated by Django 4.2.4 on 2023-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('k', models.IntegerField()),
            ],
        ),
    ]
